#!/bin/sh
# Created Fri Feb 23 10:41:19 AKST 2018
# Copyright (C) 2018 by Raymond E. Marcil <marcilr@gmail.com>
#

### BEGIN INIT INFO
# Provides:          httpd
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Apache web server (httpd)
# Description:       Apache web server (httpd)
### END INIT INFO

BIN=/usr/local/httpd-2.4.23/bin
HTTPD=${BIN}/httpd

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        echo "Starting apache..."
        ${BIN}/apachectl start
	echo "Started apache"
        ;;
  stop)
        echo "Stopping apache..."
        ${BIN}/apachectl stop
	echo "Stopped apache"
	;;
  restart|reload|force-reload)
        /etc/init.d/httpd stop
        /etc/init.d/httpd start
	;;
  version)
        ${HTTPD} -v
        ;;
  *)
        echo "Usage: /etc/init.d/blah {start|stop}"
        exit 1
        ;;

esac

exit 0
